
title: Linux no café
# email: contato[arroba-aqui]linuxnocafe.info
description: >
  Tutoriais de tecnologia e software livre desde 2014.
  Não veiculamos anúncios.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- conheca_tambem.md
- cronologia.md
- perguntas.md
- contato.md

footer_icons:
- username: Terminal Root
  url: https://terminalroot.com.br/
- username: Terminal Root TV
  url: https://www.youtube.com/TerminalRootTV/

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
