
title: Teste
email: your-email@domain.com
description: >
  Os melhores tutoriais do mundo free software você encontra aqui.
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- posts.md
- perguntas.md

footer_icons:
- username: >>> Terminal Root
  url: https://terminalroot.com.br/
- username: >>> Projeto Root
  url: https://www.youtube.com/user/projetoroot
- username: >>> Rob Braxman Tech
  url: https://www.youtube.com/c/BraxMe/featured
- username: >>> Cyberspatial
  url: https://www.youtube.com/cyberspatial
- username: >>> edureka!
  url: https://www.youtube.com/user/edurekaIN


paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
